[package]
name = "kcd_farkle_solver"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = {version = "0.18.0", features = ["rayon"]}
rayon = "1.10.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
